//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Supay.Irc.Properties {
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [DebuggerNonUserCode]
  [CompilerGenerated]
  internal class Resources {
    private static ResourceManager resourceMan;

    private static CultureInfo resourceCulture;

    [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal static ResourceManager ResourceManager {
      get {
        if (ReferenceEquals(resourceMan, null)) {
          var temp = new ResourceManager("Supay.Irc.Properties.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Advanced)]
    internal static CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The address cannot be changed while connected..
    /// </summary>
    internal static string AddressCannotBeChanged {
      get {
        return ResourceManager.GetString("AddressCannotBeChanged", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Already connected to another server..
    /// </summary>
    internal static string AlreadyConnected {
      get {
        return ResourceManager.GetString("AlreadyConnected", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Already connected to another client..
    /// </summary>
    internal static string AlreadyConnectToAnotherClient {
      get {
        return ResourceManager.GetString("AlreadyConnectToAnotherClient", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to BufferSize is limited to 8192..
    /// </summary>
    internal static string BufferSizeIsLimited {
      get {
        return ResourceManager.GetString("BufferSizeIsLimited", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Cannot read from file..
    /// </summary>
    internal static string CannotReadFromFile {
      get {
        return ResourceManager.GetString("CannotReadFromFile", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Channel cannot be empty..
    /// </summary>
    internal static string ChannelCannotBeEmpty {
      get {
        return ResourceManager.GetString("ChannelCannotBeEmpty", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The connection can not be written to yet. Wait for the Connected event..
    /// </summary>
    internal static string ConnectionCanNotBeWrittenToYet {
      get {
        return ResourceManager.GetString("ConnectionCanNotBeWrittenToYet", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Could not parse message..
    /// </summary>
    internal static string CouldNotParseMessage {
      get {
        return ResourceManager.GetString("CouldNotParseMessage", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The encoding cannot be changed while connected..
    /// </summary>
    internal static string EncodingCannotBeChanged {
      get {
        return ResourceManager.GetString("EncodingCannotBeChanged", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to ErrorMessage numerics must be between 400 and 600..
    /// </summary>
    internal static string ErrorMessageNumericsMustBeBetween {
      get {
        return ResourceManager.GetString("ErrorMessageNumericsMustBeBetween", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to A message should not be empty, nor greater than 512 characters. This message was {0} characters long..
    /// </summary>
    internal static string MessageEmptyOrTooLong {
      get {
        return ResourceManager.GetString("MessageEmptyOrTooLong", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Messages are limited to 512 characters..
    /// </summary>
    internal static string MessagesAreLimitedInSize {
      get {
        return ResourceManager.GetString("MessagesAreLimitedInSize", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to ModeAction &apos;{0}&apos; does not exist..
    /// </summary>
    internal static string ModeActionDoesNotExist {
      get {
        return ResourceManager.GetString("ModeActionDoesNotExist", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Object must be of type {0}..
    /// </summary>
    internal static string ObjectMustBeOfType {
      get {
        return ResourceManager.GetString("ObjectMustBeOfType", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The port cannot be changed while connected..
    /// </summary>
    internal static string PortCannotBeChanged {
      get {
        return ResourceManager.GetString("PortCannotBeChanged", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Server does not support accept..
    /// </summary>
    internal static string ServerDoesNotSupportAccept {
      get {
        return ResourceManager.GetString("ServerDoesNotSupportAccept", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Server does not support extended list parameter &apos;{0}&apos;..
    /// </summary>
    internal static string ServerDoesNotSupportExtendedListParameter {
      get {
        return ResourceManager.GetString("ServerDoesNotSupportExtendedListParameter", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Server does not support monitor..
    /// </summary>
    internal static string ServerDoesNotSupportMonitor {
      get {
        return ResourceManager.GetString("ServerDoesNotSupportMonitor", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Server does not support watch..
    /// </summary>
    internal static string ServerDoesNotSupportWatch {
      get {
        return ResourceManager.GetString("ServerDoesNotSupportWatch", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to The SSL property cannot be changed while connected..
    /// </summary>
    internal static string SslCannotBeChanged {
      get {
        return ResourceManager.GetString("SslCannotBeChanged", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to Target cannot be empty..
    /// </summary>
    internal static string TargetcannotBeEmpty {
      get {
        return ResourceManager.GetString("TargetcannotBeEmpty", resourceCulture);
      }
    }

    /// <summary>
    ///   Looks up a localized string similar to User &apos;{0}&apos; is not in channel &apos;{1}&apos;..
    /// </summary>
    internal static string UserIsNotInChannel {
      get {
        return ResourceManager.GetString("UserIsNotInChannel", resourceCulture);
      }
    }
  }
}
