using System;

namespace Supay.Irc.Messages
{
    /// <summary>
    /// Represents the method that will handle an <see cref="IrcMessage" /> event.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An <see cref="IrcMessageEventArgs&lt;T&gt;" /> that contains the event data.</param>
    /// <typeparam name="T">The <see cref="IrcMessage" /> generated by the event.</typeparam>
    [Serializable]
    public delegate void IrcMessageEventHandler<T>(object sender, IrcMessageEventArgs<T> e) where T : IrcMessage;

    /// <summary>
    /// Represents the method that will handle an <see cref="IrcMessage" /> cancelation event.
    /// </summary>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">A <see cref="CancelIrcMessageEventArgs&lt;T&gt;" /> that contains the event data.</param>
    /// <typeparam name="T">The <see cref="IrcMessage" /> generated by the event.</typeparam>
    [Serializable]
    public delegate void CancelIrcMessageEventHandler<T>(object sender, CancelIrcMessageEventArgs<T> e) where T : IrcMessage;
}
